name: pDL
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - rich>=10.12
  - Flask>=2.0
  - pandas>=1.1
  - numpy
  - pip:
    - nbgitpuller
    - scikit-learn
    - nltk
